# Site settings
title: OntoPortal Administration Documentation
version: 0.7.0
description: Administering the OntoPortal Virtual Appliance
baseurl: "/administration" # the subpath of your site, e.g. /blog
baseimgs: "/administration/assets/imgs" 
url: "https://ontoportal.github.io" # the base hostname & protocol for your site
opva: OntoPortal Virtual Appliance
opva_version: OntoPortal Virtual Appliance 3.0
release_version: Release 3.0.0
opa: OntoPortal Alliance
support_email: support@ontoportal.org  # for dev support only, not for end user support
twitter_username: ontoportal
github_username:  ontoportal
email: jgraybeal@stanford.edu  # not sure what this is used for


# Build settings
markdown: kramdown

collections:
  general:
    output: true
    permalink: general/:title/
  steps:
    output: true
    permalink: steps/:title/
  ontologies:
    output: true
    permalink: ontologies/:title/
  management:
    output: true
    permalink: management/:title/
