# Site settings
title: OntoPortal Administration Documentation
version: 0.3.5
email: jgraybeal@stanford.edu
description: Administering the OntoPortal Virtual Appliance
baseurl: "/administration" # the subpath of your site, e.g. /blog
baseimgs: "/administration/assets/imgs" 
url: "https://ontoportal.github.io" # the base hostname & protocol for your site
twitter_username: ontoportal
github_username:  ontoportal
support_email: support@ontoportal.org
opva: OntoPortal Virtual Appliance
opva_version: OntoPortal Virtual Appliance 3.0
release_version: Release 3.0.0
opa: OntoPortal Alliance

# Build settings
markdown: kramdown

collections:
  general:
    output: true
    permalink: general/:title/
  steps:
    output: true
    permalink: steps/:title/
  ontologies:
    output: true
    permalink: ontologies/:title/
  management:
    output: true
    permalink: management/:title/
