# Site settings
title: OntoPortal Installation Documentation
version: 0.0.1
email: jgraybeal@stanford.edu
description: Installing the OntoPortal Virtual Appliance
baseurl: "/installation" # the subpath of your site, e.g. /blog
url: "https://installation.github.io" # the base hostname & protocol for your site
twitter_username: ontoportal
github_username:  ontoportal
opva: OntoPortal Virtual Appliance
opva_version: OntoPortal Virtual Appliance 3.0

# Build settings
markdown: kramdown

collections:
  installing:
    output: true
    permalink: menus/:title/
#  maintaining:
#    output: true
#    permalink: views/:title/
#  contributing:
#    output: true
#    permalink: preferences/:title/
